{% extends 'base.html.twig' %}

{% block title %}Hello PruebaController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>




<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! âœ…</h1>

<form action="./nada2" method="post">
    <input type="text" name="user">
    <input type="password" name="pass">
    <input type="submit" value="ok">
</form> 

{% for i in 1..20 %}
    <div><h5>{{ "titulo nro: "|upper ~i}}</h5></div>
{% endfor %}


{% if param == 5 %}
    <div>Ok.</div>
{% else %}
    <div>nop</div>
{% endif %}




    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/curso_symfony4/src/Controller/PruebaController.php'|file_link(0) }}">src/Controller/PruebaController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/curso_symfony4/templates/prueba/index.html.twig'|file_link(0) }}">templates/prueba/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}
